# Production-specific configuration

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

server:
  error:
    include-stacktrace: never
  compression:
    enabled: true

# Production CORS - configure via environment variable
# Example: CORS_ALLOWED_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    com.cms.backend: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  file:
    name: /var/log/cms-backend/application.log
    max-size: 10MB
    max-history: 30

